// Regenerate the images in docs/img/ from the synthetic demo data.
//
//   node tools/screenshots.mjs
//
// Needs Chrome/Chromium (set CHROME_PATH if it isn't found) and Python.
// Everything shown is generated by tools/make_demo_db.py, never real data.

import { spawn, execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "docs", "img");
const PYTHON = process.env.PYTHON || "python3";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function findChrome() {
  for (const c of [process.env.CHROME_PATH,
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "google-chrome", "google-chrome-stable", "chromium", "chromium-browser"].filter(Boolean)) {
    if (c.includes("/")) { if (existsSync(c)) return c; continue; }
    try { return execFileSync("which", [c], { encoding: "utf8" }).trim(); } catch { /* next */ }
  }
  throw new Error("Chrome/Chromium not found; set CHROME_PATH");
}

async function connect(wsUrl) {
  const ws = new WebSocket(wsUrl);
  await new Promise((res, rej) => { ws.onopen = res; ws.onerror = rej; });
  let id = 0;
  const pending = new Map();
  ws.onmessage = (ev) => {
    const msg = JSON.parse(ev.data);
    const p = pending.get(msg.id);
    if (!p) return;
    pending.delete(msg.id);
    msg.error ? p.reject(new Error(msg.error.message)) : p.resolve(msg.result);
  };
  return {
    send: (method, params = {}) => new Promise((resolve, reject) => {
      pending.set(++id, { resolve, reject });
      ws.send(JSON.stringify({ id, method, params }));
    }),
    close: () => ws.close(),
  };
}

const tmp = mkdtempSync(join(tmpdir(), "ecobee-shots-"));
const db = join(tmp, "demo.sqlite3");
execFileSync(PYTHON, [join(ROOT, "tools", "make_demo_db.py"), "--db", db, "--hours", "48"]);
const server = spawn(PYTHON, ["-u", join(ROOT, "app", "ecobee_dashboard.py"), "--db", db, "--port", "0", "--no-open"]);
const baseUrl = await new Promise((resolve) => {
  let out = "";
  server.stdout.on("data", (d) => { out += d; const m = out.match(/(http:\/\/127\.0\.0\.1:\d+\/)/); if (m) resolve(m[1]); });
});
const profile = join(tmp, "profile");
const chrome = spawn(findChrome(), ["--headless=new", "--remote-debugging-port=0",
  `--user-data-dir=${profile}`, "--no-first-run", "--disable-gpu", "--hide-scrollbars",
  "about:blank"], { stdio: "ignore" });

try {
  const portFile = join(profile, "DevToolsActivePort");
  for (let i = 0; i < 200 && !existsSync(portFile); i++) await sleep(50);
  const port = readFileSync(portFile, "utf8").split("\n")[0];
  let page;
  for (let i = 0; i < 100 && !page; i++) {
    page = (await (await fetch(`http://127.0.0.1:${port}/json/list`)).json()).find((t) => t.type === "page");
    if (!page) await sleep(50);
  }
  const cdp = await connect(page.webSocketDebuggerUrl);
  const evaluate = async (expression) => (await cdp.send("Runtime.evaluate",
    { expression, awaitPromise: true, returnByValue: true })).result.value;
  const touch = (type, x, y) => cdp.send("Input.dispatchTouchEvent",
    { type, touchPoints: type === "touchEnd" ? [] : [{ x, y, id: 1 }] });

  async function open({ width, height, scale, mobile, scheme }) {
    await cdp.send("Emulation.setDeviceMetricsOverride", { width, height, deviceScaleFactor: scale, mobile });
    await cdp.send("Emulation.setTouchEmulationEnabled", { enabled: mobile, maxTouchPoints: mobile ? 5 : 1 });
    await cdp.send("Emulation.setEmulatedMedia", { features: [{ name: "prefers-color-scheme", value: scheme }] });
    await cdp.send("Page.navigate", { url: baseUrl });
    for (let i = 0; i < 200; i++) {
      if (await evaluate("document.querySelectorAll('#panels .chart svg').length === 3").catch(() => false)) break;
      await sleep(50);
    }
    await evaluate("localStorage.clear()");
    await sleep(300);
  }
  async function shoot(name, clip) {
    const params = { format: "png", captureBeyondViewport: !!clip };
    if (clip) params.clip = { ...clip, scale: 1 };
    const { data } = await cdp.send("Page.captureScreenshot", params);
    writeFileSync(join(OUT, name), Buffer.from(data, "base64"));
    console.log(`wrote docs/img/${name}`);
  }
  const rect = (js) => evaluate(`(() => { const r = (${js}).getBoundingClientRect();
    return { x: r.left + scrollX, y: r.top + scrollY, width: r.width, height: r.height }; })()`);
  const panel = (name) => `[...document.querySelectorAll('#panels .panel')].find(p => p.querySelector('h2').textContent === ${JSON.stringify(name)})`;

  // README hero: the whole page, desktop, dark.
  await open({ width: 930, height: 900, scale: 2, mobile: false, scheme: "dark" });
  const full = await evaluate("({ w: document.documentElement.scrollWidth, h: document.documentElement.scrollHeight })");
  await shoot("dashboard.png", { x: 0, y: 0, width: full.w, height: full.h });

  // README detail: the dehumidifier's sawtooth on the Upstairs chart.
  const chart = await rect(`${panel("Upstairs")}.querySelector('.chart')`);
  await shoot("dehumidifier-detail.png", chart);

  // User guide: one panel on desktop with a reading shown under the pointer.
  await open({ width: 930, height: 900, scale: 2, mobile: false, scheme: "light" });
  const lake = await rect(panel("Lake House"));
  const c = await rect(`${panel("Lake House")}.querySelector('.chart')`);
  const hover = { x: c.x + c.width * 0.62, y: c.y - (await evaluate("scrollY")) + 120 };
  for (const dx of [-3, 0]) {
    await cdp.send("Input.dispatchMouseEvent", { type: "mouseMoved", x: hover.x + dx, y: hover.y, pointerType: "mouse" });
    await sleep(60);
  }
  if (!await evaluate("document.querySelector('.tooltip').style.display === 'block'"))
    throw new Error("tooltip did not appear for the guide screenshot");
  await shoot("guide-panel.png", lake);

  // User guide: a phone, first screen.
  const phone = { width: 393, height: 851, scale: 2, mobile: true, scheme: "light" };
  await open(phone);
  await shoot("guide-phone.png", { x: 0, y: 0, width: 393, height: 851 });

  // User guide: a phone mid-reorder (panels collapsed, one lifted).
  await open(phone);
  await evaluate("scrollTo(0, 0)");
  // Grab the first panel's grip and drag it down past the second.
  const g0 = await evaluate(`(() => { const r = document.querySelectorAll('#panels .grip')[0].getBoundingClientRect();
    return { x: r.left + r.width / 2, y: r.top + r.height / 2 }; })()`);
  await touch("touchStart", g0.x, g0.y);
  for (let y = g0.y; y <= g0.y + 120; y += 10) { await touch("touchMove", g0.x, y); await sleep(16); }
  await sleep(250);
  await shoot("guide-reorder.png", { x: 0, y: await evaluate("scrollY"), width: 393, height: 851 });
  await touch("touchEnd");

  cdp.close();
} finally {
  chrome.kill();
  server.kill();
  await sleep(500);
  rmSync(tmp, { recursive: true, force: true, maxRetries: 10, retryDelay: 200 });
}
